import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css';
import Banner from '@/components/banner/banner.component';
import Card from '@/components/card/card.component';
import { fetchCoffeeStores } from '@/lib/coffee-stores.lib';
//import coffeeStoresData from '../data/coffee-stores.json';

export async function getStaticProps(context) {

const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const handleOnBannerButtonClick = () => {
    console.log('button clicked')
  } 
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link as='favicon' rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerButtonClick}
        />
        <div className={styles.heroImage}>
          <Image
            alt=""
            src="/static-assets/hero-image.png"
            width={800}
            height={343}
            priority
          />
        </div>

        {props.coffeeStores.length > 0 && 
        <>
        <h2 className={styles.heading2}>Greenfield stores</h2>
          <div className={styles.cardLayout}>
            {props.coffeeStores.map((coffeeStore) => {
              return (
                <Card
                  key={coffeeStore.id}
                  name={coffeeStore.name}
                  imgUrl={coffeeStore.imgUrl}
                  href={`/coffee-store/${coffeeStore.id}`}
                  className={styles.card}
                />
              );
            })}
          </div>
        </>
        }
      </main>
    </>
  );
}
