import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css';
import Banner from '../components/banner/banner.component'

export default function Home() {
  const handleOnBannerButtonClick = () => {
    console.log('button clicked')
  } 
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerButtonClick}
        />
        <div className={styles.heroImage}>
          <Image
            alt=""
            src="/../public/static-assets/hero-image.png"
            width={800}
            height={343}
          />
        </div>
      </main>
    </>
  );
}
